######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 8 08:34:28 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h comm.h server.h
SOURCES += client.cpp main.cpp server.cpp
